### ISSUE TITLE
Installation details

### ISSUE THREAD

**Issue by eburakova** [kmcgrady/streamlit-autorefresh#16]
I ran `pip install streamlit-autorefresh` in my .venv but get an import error (`ModuleNotFoundError: No module named 'streamlit_autorefresh'`). My IDE, however, sees it with no problem.

What could be the reason?

System: MacOs Ventura 13.0; (Silicon M1 chip)
Python 3.11.3

**Comment by kmcgrady** [comment]
Hey @eburakova ! Thanks for the issue. I wish I could help, but I am not sure, my only guess is some environment issue where your IDE might see in in that environment, but not in running? It's really bizarre!

Closing this issue because I don't see a n issue with streamlit-autorefresh, but let me know if you receive any more insight.

**Comment by eburakova** [comment]
Hey @kmcgrady, indeed, this was a false alarm - in fact it appears to be a more general issue of Streamlit. I recently faced the same error when I installed other packages. It has to do something with streamlit cache. I will open an issue there!
